### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by amiedes** [amiedes/consul#3]
- [x] Remove unused `http` gem
- [x] Handle all possible errors in `GraphqlController`
- [x] Write tests for uncovered code: `HasPublicAuthor` module and `public_voter` method from `User` class
- [x] Truncate votes timestamp to day or hour (use method)
- [x] Disable `graphiql-rails` for production
- [x] Read `API_TYPE_DEFINITIONS` from `.yml` file
- [x] Use `age_range` instead of `date_of_birth` when exposing `Voter` class
- [x] Establish thresholds when showing voters info. ¿Should this be customizable for forks?
- [x] Fix *TODO* in `type_creator.rb`, line 69 ==> Fix this shit. Also happens for `ProposalNotification`. Search for the bug in `TypeCreator`, I think there's no need to make exceptions.
- [x] Refactor `TypeCreator` => Add method to generate `QueryRoot` (so `graphql.rb` initializer has less code).
- [x] Ask for advice for `GraphQL::AssociationResolver` testing. Is it too coupled to implementation? Maybe need to mock?
- [x] Fix QueryTypeCreator failing spec
- [ ] Add all remaining relevant `connection` fields
- [ ] Re-investingate the approach to make `alias_for` for GraphQL types (what happended with `Voter`)
- [ ] Shoud the resolvers have their own dedicated tests?
- [ ] If Organizations can't be exposed, I'll have to 'fake' them so I can test the generation of :has_one associations
